# AzusaNametag Configuration

messages:
# Message when show/hide is successful
  hide_nametag_success: "§aSuccessfully hidden all players nametags."
  remove_nametag_success: "§aSuccessfully restored all players nametags."

# Message when show/hide has been used before
  already_hidden_nametag: "§cAll players nametags are already hidden."
  already_visible_nametag: "§cAll players nametags are already visible."

# Broadcast message to all players
broadcast:
  hide_nametag: "§eAll players §fnametags have been hidden by an admin."
  show_nametag: "§eAll players §fnametags have been restored by an admin."
